version: '3'

tasks:
  viewscreen:
    desc: Deploy viewscreen (HTPC)
    cmds:
      # using --boot since the activation breaks the user's systemd
      - deploy --boot .#viewscreen 
      # - nix run github:nix-community/nixos-anywhere -- --flake .#viewscreen root@viewscreen

  viewscreen-vm:
    desc: Deploy viewscreen in a virtual machine
    cmds:
      - nix build .#nixosConfigurations.viewscreen.config.system.build.vm
      - ./result/bin/run-viewscreen-vm
